// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "amount", Type: field.TypeString, Nullable: true},
		{Name: "currency_code", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// AccountHistoriesColumns holds the columns for the "account_histories" table.
	AccountHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "amount", Type: field.TypeString, Nullable: true},
		{Name: "currency_code", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "account_accounthistory", Type: field.TypeInt, Nullable: true},
	}
	// AccountHistoriesTable holds the schema information for the "account_histories" table.
	AccountHistoriesTable = &schema.Table{
		Name:       "account_histories",
		Columns:    AccountHistoriesColumns,
		PrimaryKey: []*schema.Column{AccountHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_histories_accounts_accounthistory",
				Columns:    []*schema.Column{AccountHistoriesColumns[8]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		AccountHistoriesTable,
	}
)

func init() {
	AccountHistoriesTable.ForeignKeys[0].RefTable = AccountsTable
}
