// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LintaoAmons/undercontrol/ent/accounthistory"
	"github.com/LintaoAmons/undercontrol/ent/predicate"
)

// AccountHistoryDelete is the builder for deleting a AccountHistory entity.
type AccountHistoryDelete struct {
	config
	hooks    []Hook
	mutation *AccountHistoryMutation
}

// Where appends a list predicates to the AccountHistoryDelete builder.
func (ahd *AccountHistoryDelete) Where(ps ...predicate.AccountHistory) *AccountHistoryDelete {
	ahd.mutation.Where(ps...)
	return ahd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ahd *AccountHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ahd.sqlExec, ahd.mutation, ahd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ahd *AccountHistoryDelete) ExecX(ctx context.Context) int {
	n, err := ahd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ahd *AccountHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accounthistory.Table, sqlgraph.NewFieldSpec(accounthistory.FieldID, field.TypeInt))
	if ps := ahd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ahd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ahd.mutation.done = true
	return affected, err
}

// AccountHistoryDeleteOne is the builder for deleting a single AccountHistory entity.
type AccountHistoryDeleteOne struct {
	ahd *AccountHistoryDelete
}

// Where appends a list predicates to the AccountHistoryDelete builder.
func (ahdo *AccountHistoryDeleteOne) Where(ps ...predicate.AccountHistory) *AccountHistoryDeleteOne {
	ahdo.ahd.mutation.Where(ps...)
	return ahdo
}

// Exec executes the deletion query.
func (ahdo *AccountHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ahdo.ahd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accounthistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ahdo *AccountHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := ahdo.Exec(ctx); err != nil {
		panic(err)
	}
}
