// Code generated by gonstructor --type=PostgresConfigs --constructorTypes=builder; DO NOT EDIT.

package common

type PostgresConfigsBuilder struct {
	user     string
	password string
	host     string
	port     string
	dbname   string
	sslmode  string
}

func NewPostgresConfigsBuilder() *PostgresConfigsBuilder {
	return &PostgresConfigsBuilder{}
}

func (b *PostgresConfigsBuilder) User(user string) *PostgresConfigsBuilder {
	b.user = user
	return b
}

func (b *PostgresConfigsBuilder) Password(password string) *PostgresConfigsBuilder {
	b.password = password
	return b
}

func (b *PostgresConfigsBuilder) Host(host string) *PostgresConfigsBuilder {
	b.host = host
	return b
}

func (b *PostgresConfigsBuilder) Port(port string) *PostgresConfigsBuilder {
	b.port = port
	return b
}

func (b *PostgresConfigsBuilder) Dbname(dbname string) *PostgresConfigsBuilder {
	b.dbname = dbname
	return b
}

func (b *PostgresConfigsBuilder) Sslmode(sslmode string) *PostgresConfigsBuilder {
	b.sslmode = sslmode
	return b
}

func (b *PostgresConfigsBuilder) Build() *PostgresConfigs {
	return &PostgresConfigs{
		user:     b.user,
		password: b.password,
		host:     b.host,
		port:     b.port,
		dbname:   b.dbname,
		sslmode:  b.sslmode,
	}
}
