//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AccountHistory = newAccountHistoryTable("public", "account_history", "")

type accountHistoryTable struct {
	postgres.Table

	//Columns
	ID           postgres.ColumnInteger
	Name         postgres.ColumnString
	Amount       postgres.ColumnString
	CurrencyCode postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	CreatedBy    postgres.ColumnString
	UpdatedAt    postgres.ColumnTimestampz
	UpdatedBy    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AccountHistoryTable struct {
	accountHistoryTable

	EXCLUDED accountHistoryTable
}

// AS creates new AccountHistoryTable with assigned alias
func (a AccountHistoryTable) AS(alias string) *AccountHistoryTable {
	return newAccountHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AccountHistoryTable with assigned schema name
func (a AccountHistoryTable) FromSchema(schemaName string) *AccountHistoryTable {
	return newAccountHistoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AccountHistoryTable with assigned table prefix
func (a AccountHistoryTable) WithPrefix(prefix string) *AccountHistoryTable {
	return newAccountHistoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AccountHistoryTable with assigned table suffix
func (a AccountHistoryTable) WithSuffix(suffix string) *AccountHistoryTable {
	return newAccountHistoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAccountHistoryTable(schemaName, tableName, alias string) *AccountHistoryTable {
	return &AccountHistoryTable{
		accountHistoryTable: newAccountHistoryTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newAccountHistoryTableImpl("", "excluded", ""),
	}
}

func newAccountHistoryTableImpl(schemaName, tableName, alias string) accountHistoryTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		NameColumn         = postgres.StringColumn("name")
		AmountColumn       = postgres.StringColumn("amount")
		CurrencyCodeColumn = postgres.StringColumn("currency_code")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		CreatedByColumn    = postgres.StringColumn("created_by")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		UpdatedByColumn    = postgres.StringColumn("updated_by")
		allColumns         = postgres.ColumnList{IDColumn, NameColumn, AmountColumn, CurrencyCodeColumn, CreatedAtColumn, CreatedByColumn, UpdatedAtColumn, UpdatedByColumn}
		mutableColumns     = postgres.ColumnList{NameColumn, AmountColumn, CurrencyCodeColumn, CreatedAtColumn, CreatedByColumn, UpdatedAtColumn, UpdatedByColumn}
	)

	return accountHistoryTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Name:         NameColumn,
		Amount:       AmountColumn,
		CurrencyCode: CurrencyCodeColumn,
		CreatedAt:    CreatedAtColumn,
		CreatedBy:    CreatedByColumn,
		UpdatedAt:    UpdatedAtColumn,
		UpdatedBy:    UpdatedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
