// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AccountHistory is the predicate function for accounthistory builders.
type AccountHistory func(*sql.Selector)
